# Generated by Django 6.1.1 on 2026-10-01 09:50

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'objects', 'ordering': ['created_at']},
        ),
        migrations.AlterModelManagers(
            name='message',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
